### ISSUE TITLE
Milestone 1 Meeting Notes

### ISSUE THREAD

**Issue by williamxu7** [UBC-MDS/522-Group_30-Rockstars#2]
- Reviewed example final project in milestone 1, discussed the file organization

- Plan to create teamwork contract (through class activity, scheduling, things we can anticipate), code of conduct (respectful behavior), contributing file (operation on interactions), license file(use open source license). Customized some of the content

- Forking repo walkthrough

- Dataset brainstorming: inference or prediction
Options: Vancouver housing prices (big dataset, suitable for inference, eliminated for now), Strathcona housing prices (pure prediction, target class would be assessment value), Coronavirus dataset (could do an inference), Gapminder dataset (regression or inference)
Vote for the dataset: Strathcona housing prices (prediction problem)
[Strathocona website](https://data.strathcona.ca/browse?q=property%20assessment&sortBy=relevance)

- Task file delegation

- Meeting scheduled at 5:30pm today

**Comment by danielon-5** [comment]
Meeting02
11/18/2020
5:30pm PST

- Reviewed LICENSE text file in the group project repository

- Discussed the process for creating the .md documents through RStudio
- Discussed the process of pushing to our personal repos
- Agreed on how we will work for the project proposal through the following link: https://docs.google.com/document/d/1Bpc4a09WNy4WuGuI8jiDkxI6losJ0u5XHvn45RPFZ2E/edit?usp=sharing
- Agreed that the question to answer would be: **"We want to build a predictive model for the property assessment value for single family dwellings in Strathcona County, AB, Canada."**
- Discussed the process for carrying out the preliminary EDA for predictive models (Read data set, filter, split into TRAIN and TEST, carry out EDA ONLY ON TRAIN)
- Next meetings: Friday 2-4pm PST, Saturday 9:30am-inf (11:30ish)
- Assigned documents should be finalized for Friday meeting
- Commit to go through points 3, 4 and 5 of the project proposal before Friday meeting

**Comment by danielon-5** [comment]
Meeting03
11/20/2020
2:00pm PST

1. Reviewed the process of creating files in individual repos, add them, commit, push and create pull requests
2. Finished pushing to the group repo the LICENSE, CONTRIBUTING, CODE_OF_CONDUCT, README and team_working_contract files as well as file and directory setup
3. William granted contributing access permissions to the team
4. Went through the project proposal document that we were working here: https://docs.google.com/document/d/1Bpc4a09WNy4WuGuI8jiDkxI6losJ0u5XHvn45RPFZ2E/edit#
5. Reviewed the data set and noticed that the 2020 did not have the 'asset class' attribute
6. Decided on changing the data set to the 2018 one that has that attribute
7. Went through some EDA proposals of heatmaps made by William
8. Jordon and Cal suggested some density repeated plots for binary variables (e.g. fireplace, basement, etc.) and some scatter plots for size and assessed value
9. Went through the python script made by William to read the csv file
10. Daniel will figure out the submission details and if Introduction, Usage and Dependencies section of the README file are for Milestone1
11. Next meeting to finish the deliverable requirements and submit: 11/21/20 at 9:30am PST

**Comment by williamxu7** [comment]
I have made some revisions on the heatmap (dropped some features) and I added a scatter plot for size and assessment value.

**Comment by danielon-5** [comment]
Meeting03
11/21/2020
9:30am PST

1. Went through some preliminary EDA plots made by William
2. Wrote a short description for every plot
3. Ensured a 4-eye principle for the descriptions written by each other
4. Updated the .ipynb document in the src folder
5. Created a v1.0 release for this Milestone 1
6. Updated the TO DO list issue
7. Referenced the EDA document in the README file
8. Submitted assignment
