### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/522-Group_30-Rockstars#20]
- Try to avoid using function names and abbreviations like `ColumnTransformer` and 'MAPE'. Instead, define them first.

- It will add a lot to the proposal to describe the dataset in more detail and clarify which variables would have large effect on your dependent variable.

**Comment by williamxu7** [comment]
Thank you for the feedback, Hossam. We will make suggested adjustments in our Milestone 2.
