### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/522-Group_30-Rockstars#49]
Hi guys! Great work on this project and some interesting results you shown. My feedback is small details mainly just around the documentation, analysis/reasoning and suggestions on communication.

Documentation - it is great overall. The only comment would be to have a raw data folder and processed data folder. I know that you have adapted the file names accordingly but perhaps for future. 

Code - it is great!

Analysis/reasoning - somewhat 
1. Usage of words like "hyperparameter" under the analysis section of your report - this may not make sense to a wider audience. I am referencing this post from Varada who said it best: https://ubc-mds.slack.com/archives/C24J4AVFZ/p1606457033427100
2. I am also unable to see your coefficients table under analysis!
3. Under the Limitations + Future section, you mention that for future, you will do Random Forest Regression but you have done your regression analysis above! 
4. I don't see your references under the references section. 

Other general suggestions -
1. Your readme usage section should be updated to reflect the new make all code rather than the individual scripts! So the user should just be able to run - "make all" rather than the scripts individually. 
2. The first part of your readme mentions breast cancer images but your project is actually about housing prices in Alberta! This may just have been an oversight when copying over Tiffany's read me file. 
3. You have produced a great makefile png but I wish it could be seen on the Readme file.

**Comment by danielon-5** [comment]
Hi Javaira,

Thank you very much for your detailed and meaningful feedback. We are taking action to address every issue and suggestion. Again, we appreciate you taking the time to contribute to our project in such an important manner.

Stay tuned =)
