### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by ChuckHo777** [UBC-MDS/522-Group_30-Rockstars#50]
Hi Guys, 

Great work and interesting analysis.  

Below are some comments on minor details in the Readme page, folder organization, and the report.

**Readme:**
-	**About**: We need to update the summary of the project.
-	**Usage:** We need to update to using the makefile instead of individual scripts.
-	**Dependencies:** Great to have: a yaml file to ease off the installation of dependencies in the early milestones. (Good to have)

**Folder organization:**
-	**Data Folder:** We may want to consider further split into two folders: raw and processed.

**Report:**

- **Introduction:** We can consider highlighting the purpose of the study again along with the provided context in this section.

- **EDA:** The box plots for binary features are a bit hard to see, may consider break it into 2 line and enlarge the size of each graph in order to make the box and median more visible. 

- **Analysis:**
      - I am not able to find the mentioned coefficient table, may need to check the Rmd file see if it renders properly. 
      - Great if we elaborate more on the reason of picking Ridge Regression model (e.g., for easier or better interpretation of feature importance or better test score with test data, etc.). 
      - It is a bit hard to instantly link the test score of 0.788 as the R square score with test data for the Ridge Regression model as we didn’t elaborate on it in the Ridge Regression write-up (e.g., it is having a comparable score with the validation score) and It is a bit too close to the multiple model score table where the test scores are validation scores with the train data.

**Comment by danielon-5** [comment]
Hi Chuck Ho,

Those are great points and suggestions, thank you so much. We will be addressing every issue and suggestion for this last Milestone. The project will definitely improve after your collaboration.

Thanks again! =)
