### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/522-Group_30-Rockstars#61]
Thanks for your submission. I created a virtual environment and installed your dependencies to try to run your make file. I like that you provide helpful comments throughout the makefile. The README lacks documentation about using the make file. Also, I suggest you create an env yaml file to make things easier for users to install dependencies.

**Comment by williamxu7** [comment]
Thank you very much for the feedback on Milestone 3, Hossam! Have a great holiday!
